### ISSUE TITLE
Possible to pass https.Agent options

### ISSUE THREAD

**Issue by dvonlehman** [TooTallNate/node-https-proxy-agent#11]
I've been using https-proxy-agent with great success to make aws-sdk calls through a corporate proxy like so:

~~~js
awsConfig.httpOptions.agent = new HttpsProxyAgent(process.env.HTTPS_PROXY);
~~~

However there is [known node issue](https://github.com/aws/aws-sdk-js/issues/862) connecting to DynamoDB that requires setting the agent like so:

~~~js
awsConfig.httpOptions.agent = new https.Agent({
  rejectUnauthorized: true,
  keepAlive: true,                // workaround part i.
  secureProtocol: 'TLSv1_method', // workaround part ii.
  ciphers: 'ALL'                  // workaround part ii.
});
~~~

I don't see how to pass `keepAlive`, `secureProtocol`, and `ciphers` to the https-proxy-agent.

**Comment by TooTallNate** [comment]
Try doing:

```js
var opts = url.parse(process.env.HTTPS_PROXY);
opts.rejectUnauthorized: true;
opts.keepAlive: true;                // workaround part i.
opts.secureProtocol: 'TLSv1_method'; // workaround part ii.
opts.ciphers: 'ALL';                  // workaround part ii.

awsConfig.httpOptions.agent = new HttpsProxyAgent(opts);
```

**Comment by dvonlehman** [comment]
Thanks Nate for the quick response. That appears to be doing the trick. I've incorporated it into my little helper module: https://www.npmjs.com/package/aws-config

**Comment by unni1** [comment]
Sorry for this newbie question. I googled a lot, but couldn't find an answer, may be I was not using the right keywords.

I also was facing the same issue and AWS support advised us to use https.agent. But I ran into some trouble with the company proxy. Finally, with pac-proxy-agent, I could get it to work with the below code sample:

```
const pacProxyAgent = require('pac-proxy-agent'); 

const pacProxyUri = 'pac+http://proxy.com/proxy.pac'

var ec2Agent = new pacProxyAgent({
	uri: pacProxyUri,
	ciphers: "ALL",
	secureProtocol: "TLSv1_method"
});

var ec2 = new AWS.EC2({
	httpOptions: {
		agent: ec2Agent,
	},
	region: 'us-east-1'
}); 
```

I don't see any errors in the node.js log, but I am not sure if it is actually obeying the 
`secureProtocol: `"TLSv1_method"``
part. 

I have this confusion because I randomly changed it to some other string, say "ABCv1", and it still didn't give me any errors. In Wireshark, I saw all the ClientHello messages to the AWS where TLSv1.2, but I don't know if I was looking at the right place.

If I want to force TLSv1, is the above code sample correct?
